import { Project } from '../models/project';

/**
 * Mock project orders (Projektaufträge) for the city of Braunschweig.
 * Stand-in for the data that will later come from the PDF-processing backend.
 */
export const MOCK_PROJECTS: readonly Project[] = [
  {
    id: 'P-2024-001',
    projekttitel: 'Erneuerung Mittelspannungsnetz Weststadt',
    auftragsgruende: 'Altersbedingter Austausch der Kabelstrecken zur Versorgungssicherheit.',
    itSystemAenderungen: 'Aktualisierung Netzleitsystem, neue Schaltzustände einpflegen.',
    sparte: 'Strom',
    sparteDetails: 'Mittelspannung 20 kV, Erdkabel inkl. Muffen',
    kostenstelle: 'KST-4101',
    kosten: {
      materialkosten: 420000,
      fremdleistungen: 310000,
      eigenleistungen: 180000,
      ingenieurleistungDritte: 95000,
      zuschlaege: 45000,
      gesamtkosten: 1050000,
    },
    zahlungsplan: [
      { year: 2024, amount: 350000 },
      { year: 2025, amount: 500000 },
      { year: 2026, amount: 200000 },
    ],
    leitungslaengeMeter: 4200,
    preisProMeter: 250,
  },
  {
    id: 'P-2024-002',
    projekttitel: 'Gasdruckregelstation Schunteraue',
    auftragsgruende: 'Kapazitätserweiterung für Neubaugebiet im Norden.',
    itSystemAenderungen: 'Anbindung Fernwirktechnik an Prozessleitsystem.',
    sparte: 'Gas',
    sparteDetails: 'Neubau GDRM-Station inkl. Anbindung Hochdruckleitung',
    kostenstelle: 'KST-4205',
    kosten: {
      materialkosten: 260000,
      fremdleistungen: 240000,
      eigenleistungen: 90000,
      ingenieurleistungDritte: 70000,
      zuschlaege: 30000,
      gesamtkosten: 690000,
    },
    zahlungsplan: [
      { year: 2024, amount: 240000 },
      { year: 2025, amount: 450000 },
    ],
    leitungslaengeMeter: 1500,
    preisProMeter: 180,
  },
  {
    id: 'P-2024-003',
    projekttitel: 'Trinkwasserleitung Sanierung Innenstadt',
    auftragsgruende: 'Hohe Schadensrate und Wasserverluste in Graugussleitungen.',
    itSystemAenderungen: 'Keine.',
    sparte: 'Wasser',
    sparteDetails: 'Austausch Grauguss gegen Duktilguss DN 200',
    kostenstelle: 'KST-4310',
    kosten: {
      materialkosten: 510000,
      fremdleistungen: 380000,
      eigenleistungen: 210000,
      ingenieurleistungDritte: 60000,
      zuschlaege: 40000,
      gesamtkosten: 1200000,
    },
    zahlungsplan: [
      { year: 2025, amount: 600000 },
      { year: 2026, amount: 600000 },
    ],
    leitungslaengeMeter: 3000,
    preisProMeter: 400,
  },
  {
    id: 'P-2025-004',
    projekttitel: 'Glasfaser-Backbone Technologiepark',
    auftragsgruende: 'Digitale Anbindung von Umspannwerken und Gewerbegebiet.',
    itSystemAenderungen: 'Neues Monitoring, Integration in Netzwerk-Management.',
    sparte: 'Infotechnik',
    sparteDetails: 'Leerrohrverbund mit Glasfaser, 96 Fasern',
    kostenstelle: 'KST-4420',
    kosten: {
      materialkosten: 180000,
      fremdleistungen: 220000,
      eigenleistungen: 70000,
      ingenieurleistungDritte: 50000,
      zuschlaege: 20000,
      gesamtkosten: 540000,
    },
    zahlungsplan: [
      { year: 2025, amount: 300000 },
      { year: 2026, amount: 240000 },
    ],
    leitungslaengeMeter: 6000,
    preisProMeter: 90,
  },
  {
    id: 'P-2025-005',
    projekttitel: 'Fernwärme-Ausbau Quartier Heidberg',
    auftragsgruende: 'Dekarbonisierung der Wärmeversorgung im Bestandsquartier.',
    itSystemAenderungen: 'Hausübergabestationen an Leitsystem anbinden.',
    sparte: 'Fernwaerme',
    sparteDetails: 'Verlegung Vor- und Rücklauf, vorgedämmte Rohre DN 150',
    kostenstelle: 'KST-4530',
    kosten: {
      materialkosten: 640000,
      fremdleistungen: 520000,
      eigenleistungen: 240000,
      ingenieurleistungDritte: 110000,
      zuschlaege: 60000,
      gesamtkosten: 1570000,
    },
    zahlungsplan: [
      { year: 2025, amount: 470000 },
      { year: 2026, amount: 700000 },
      { year: 2027, amount: 400000 },
    ],
    leitungslaengeMeter: 2800,
    preisProMeter: 560,
  },
  {
    id: 'P-2025-006',
    projekttitel: 'Niederspannungs-Verstärkung Östliches Ringgebiet',
    auftragsgruende: 'Lastzuwachs durch Wärmepumpen und Wallboxen.',
    itSystemAenderungen: 'Smart-Meter-Gateway-Anbindung erweitern.',
    sparte: 'Strom',
    sparteDetails: 'Niederspannung 0,4 kV, zusätzliche Ortsnetzstation',
    kostenstelle: 'KST-4108',
    kosten: {
      materialkosten: 300000,
      fremdleistungen: 200000,
      eigenleistungen: 150000,
      ingenieurleistungDritte: 40000,
      zuschlaege: 30000,
      gesamtkosten: 720000,
    },
    zahlungsplan: [
      { year: 2025, amount: 320000 },
      { year: 2026, amount: 400000 },
    ],
    leitungslaengeMeter: 2600,
    preisProMeter: 210,
  },
  {
    id: 'P-2026-007',
    projekttitel: 'Wasserwerk Bienrode Filtermodernisierung',
    auftragsgruende: 'Erhöhung der Aufbereitungskapazität und Energieeffizienz.',
    itSystemAenderungen: 'Prozessleittechnik-Update, neue Sensorik.',
    sparte: 'Wasser',
    sparteDetails: 'Erneuerung Mehrschichtfilter, Pumpentechnik',
    kostenstelle: 'KST-4315',
    kosten: {
      materialkosten: 380000,
      fremdleistungen: 290000,
      eigenleistungen: 120000,
      ingenieurleistungDritte: 80000,
      zuschlaege: 35000,
      gesamtkosten: 905000,
    },
    zahlungsplan: [
      { year: 2026, amount: 505000 },
      { year: 2027, amount: 400000 },
    ],
    leitungslaengeMeter: 350,
    preisProMeter: 0,
  },
];
