# Generated by Django 5.2 on 2026-06-17 14:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung')),
                ('abbreviation', models.CharField(blank=True, max_length=20, verbose_name='Kürzel')),
            ],
            options={
                'verbose_name': 'Sparte',
                'verbose_name_plural': 'Sparten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Straße')),
            ],
            options={
                'verbose_name': 'Straße',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='trade', serialize=False, to='core.asset')),
            ],
            options={
                'verbose_name': 'Gewerk',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255, verbose_name='Projekttitel')),
                ('fiscal_year', models.PositiveSmallIntegerField(help_text='Wird auch als Referenzjahr für die Jahresauswertung verwendet.', verbose_name='Geschäftsjahr')),
                ('execution_start', models.DateField(verbose_name='Ausführungszeit von')),
                ('execution_end', models.DateField(verbose_name='Ausführungszeit bis')),
                ('reason', models.TextField(verbose_name='Antragsgrund')),
                ('psp_element', models.CharField(max_length=50, verbose_name='PSP-Element')),
                ('pipe_length_m', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Leitungs-/Trassenlänge der Maßnahme (m)')),
                ('cost_per_meter', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Euro pro Meter Trassenlänge (€/m)')),
                ('material_costs', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Materialkosten netto (€)')),
                ('external_services', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Fremdleistungen (€)')),
                ('internal_services', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Eigenleistungen (€)')),
                ('engineering_services', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingenieurleistungen Dritte (€)')),
                ('material_surcharge_rate', models.DecimalField(decimal_places=4, default=Decimal('0.17'), help_text='Prozentualer Aufschlag auf die Materialkosten netto (Standard: 0,17 = 17 %).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Zuschlagssatz Materialkosten')),
                ('investment_surcharge_rate', models.DecimalField(decimal_places=4, default=Decimal('0.23'), help_text='Prozentualer Aufschlag auf die Gesamtkosten ohne Zuschläge (Standard: 0,23 = 23 %).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Zuschlagssatz Investition')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Summe aus Materialkosten, Fremd-, Eigen- und Ingenieurleistungen. Wird automatisch berechnet.', max_digits=14, verbose_name='Zwischenkosten (€)')),
                ('material_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Zuschlagssatz Material × Materialkosten netto. Wird automatisch berechnet.', max_digits=14, verbose_name='Materialkostenzuschläge (€)')),
                ('investment_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Zuschlagssatz Investition × Gesamtkosten ohne Zuschläge. Wird automatisch berechnet.', max_digits=14, verbose_name='Investitionszuschläge (€)')),
                ('total_surcharges', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Summe aus Materialkostenzuschlägen und Investitionszuschlägen. Wird automatisch berechnet.', max_digits=14, verbose_name='Zwischensumme Zuschläge (€)')),
                ('total_costs', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Gesamtkosten ohne Zuschläge zuzüglich aller Zuschläge. Wird automatisch berechnet.', max_digits=14, verbose_name='Gesamtkosten (€)')),
                ('payment_schedule', models.JSONField(default=list, help_text='Liste monatlicher Zahlungsraten über 3 Jahre.', verbose_name='Zahlungsplan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt geändert am')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.asset', verbose_name='Asset')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.division', verbose_name='Sparte')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.street', verbose_name='Straße')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.trade', verbose_name='Gewerk')),
            ],
            options={
                'verbose_name': 'Antrag',
                'verbose_name_plural': 'Anträge',
                'ordering': ['-fiscal_year', 'project_title'],
            },
        ),
    ]
