# Generated by Django 5.2 on 2026-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='engineering_services',
        ),
        migrations.RemoveField(
            model_name='application',
            name='external_services',
        ),
        migrations.RemoveField(
            model_name='application',
            name='internal_services',
        ),
        migrations.RemoveField(
            model_name='application',
            name='investment_surcharge',
        ),
        migrations.RemoveField(
            model_name='application',
            name='material_costs',
        ),
        migrations.RemoveField(
            model_name='application',
            name='material_surcharge',
        ),
        migrations.RemoveField(
            model_name='application',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_costs',
        ),
        migrations.RemoveField(
            model_name='application',
            name='total_surcharges',
        ),
        migrations.AddField(
            model_name='application',
            name='planned_engineering_services',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Ingenieurleistungen Dritte (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_external_services',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Fremdleistungen (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_internal_services',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Eigenleistungen (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_investment_surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Investitionszuschläge (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_material_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Materialkosten netto (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_material_surcharge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Materialkostenzuschläge (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Zwischenkosten 1.-4. (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_total_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Gesamtkosten (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='planned_total_surcharges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Zwischensumme Zuschläge 5.-8. (geplant)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='real_engineering_services',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Ingenieurleistungen Dritte (real)'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_external_services',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Fremdleistungen (real)'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_internal_services',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Eigenleistungen (real)'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_investment_surcharge',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Investitionszuschläge (real)'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_material_costs',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Materialkosten netto (real)'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_material_surcharge',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Materialkostenzuschläge (real)'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_total_costs',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, verbose_name='Gesamtkosten (real)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='investment_surcharge_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Zuschlagssatz Investition'),
        ),
        migrations.AlterField(
            model_name='application',
            name='material_surcharge_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Zuschlagssatz Materialkosten'),
        ),
    ]
