# Generated by Django 5.2 on 2026-06-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_application_engineering_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sha256',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='SHA256-Prüfsumme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='cost_per_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Euro pro Meter Trassenlänge (€/m)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.street', verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='application',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.trade', verbose_name='Gewerk'),
        ),
    ]
