# Generated by Django 5.2 on 2026-06-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_sha256_alter_application_cost_per_meter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-fiscal_year', 'project_title'], 'verbose_name': 'Antrag auf Mittelfreigabe', 'verbose_name_plural': 'Anträge auf Mittelfreigabe'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Straße', 'verbose_name_plural': 'Straßen'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': 'Gewerk', 'verbose_name_plural': 'Gewerke'},
        ),
    ]
