# Generated by Django 5.2 on 2026-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_application_options_alter_street_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='execution_start',
            field=models.TextField(verbose_name='Ausführungszeit von'),
        ),
        migrations.AlterField(
            model_name='application',
            name='execution_end',
            field=models.TextField(verbose_name='Ausführungszeit bis'),
        ),
    ]
