# Generated by Django 5.2 on 2026-06-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_application_options_alter_street_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.division', verbose_name='Sparte'),
        ),
    ]
