# Generated by Django 5.2 on 2026-06-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_application_execution_start_and_more'),
        ('core', '0005_asset_division'),
    ]

    operations = [
    ]
